package  { 
	/**
	import flash.display.MovieClip;
	 * Implementer indicates it's a Script SWF (no UI elements) generated by MTASC
	 * that has a main() method to be called by the BootStrapper.
	 * @author Troy Gardner
	 */
	interface com.troyworks.framework.bootstrapper.IScriptSwf {
		/*
		 * If this is called (automatically) by MTASC it will be 
		 * passed a refence to the Script.swf
		 * 
		 * passing null, should fire off the registerclasses.
		 * 
		 */
	//static types not allowed 	public static function run(container : MovieClip) : void;
	
	}
}